Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202510.26.0"
    config.vm.synced_folder ".", "/vagrant_shared"
    
    config.vm.define "cde-sousS" do |control|
        control.vm.hostname = "cde-sousS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provision "shell", path: "./scripts/setup-k3s.sh", args: ["server", "192.168.56.110", ""]
        control.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
            v.name = "cde-sousS"
        end
    end
end
