Vagrant.configure("2") do |config|
	config.vm.box = "alvistack/ubuntu-24.04"
	config.vm.box_version = "20260108.1.1"
    config.vm.synced_folder "./confs", "/confs"
    config.vm.synced_folder "./websites", "/websites"
    
    config.vm.define "cde-sousS" do |control|
        control.vm.hostname = "cde-sousS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provision "shell", path: "./scripts/setup-k3s.sh", args: ["192.168.56.110"]
        control.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
            v.name = "cde-sousS"
        end
    end

    config.trigger.after :up do |trigger|
        trigger.run = {path: "./scripts/post-install.sh", args:["cde-sousS"]}
        trigger.only_on = "cde-sousS"
    end
end
