Vagrant.configure("2") do |config|
	config.vm.box = "alvistack/ubuntu-24.04"
	config.vm.box_version = "20260108.1.1"
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end
	config.vm.define "cde-sous" do |control|
		control.vm.hostname = "cde-sousS"
		control.vm.network "public_network", ip: "192.168.56.110", hostname: true
	end
	config.vm.define "pgimeno" do |control|
		control.vm.hostname = "pgimenoSW"
		control.vm.network "public_network", ip: "192.168.56.111", hostname: true
	end
end